
version: '3.9'

services:
  postgres:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: library_api

  app:
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
